# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9646d939b64b7bebcc9d30435cdaa57dbab784eae73fd267686321bf8ac5a43ff9a697cc5c90dfd1bde8985d3e2bb3f9b48d41ff4ccff89389bc0305a5590d31

test:
  secret_key_base: 37f0f29d6821f0b6c1b2844847b8ec62a65d14ad50275f64e4d74d805722619a5173a3dccd72b7dbec89bb4668a70b13ee4bb83df02d9aca83caf394fcf11161

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
